# -*- coding: utf-8 -*-
from time import sleep
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon, QTransform
from PyQt5.QtCore import QSize
import pytesseract
import easygui
from PIL import Image
import docx
import os
import arabic_reshaper
from bidi.algorithm import get_display
import io
import fitz  # PyMuPDF
import tkinter as tk
from tkinter import filedialog
import requests
from googletrans import Translator
import webbrowser


# Form implementation generated from reading ui file 'main2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1273, 791)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("B Zar")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QWidget{\n"
"    border: none;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.translate_tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Terafik")
        font.setPointSize(18)
        self.translate_tab.setFont(font)
        self.translate_tab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.translate_tab.setStyleSheet("\n"
"QTextEdit {\n"
"    border: 0.5px solid #4A4A4A;  \n"
"    border-radius: 10px;        \n"
"    padding: 5px;              \n"
"    background-color: #FFFFFF;  \n"
"    color: #000000;    \n"
"    direction: rtl\n"
"}\n"
"QTextEdit[placeholder]:empty {\n"
"    line-height: 200px; /* این مقدار را متناسب با ارتفاع QTextEdit تنظیم کنید */\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTableWidget::horizontalHeader {\n"
"    visibility: hidden;\n"
"}\n"
"\n"
"QTableWidget::verticalHeader{\n"
"    visibility: false;\n"
"}\n"
"QTableWidget {\n"
"    border: none;\n"
"}\n"
"\n"
"QTableWidget QScrollBar {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"\n"
"QPushButton {\n"
"                background-color:rgb(255, 255, 255,0.0);\n"
"                color: rgb(94, 92, 100); \n"
"                border: none;\n"
"                  border-radius:0px;\n"
"                text-align: center;\n"
"                text-decoration: none;\n"
"                transition-duration: 0.4s;\n"
"                cursor: pointer;\n"
"                  selection-background-color: rgb(94, 92, 100);\n"
"            }\n"
"            QPushButton:hover {\n"
"                  color:rgb(61, 56, 70);\n"
"                background-color: rgb(192, 191, 188, 0.3);\n"
"                  font-size: 14px;\n"
"            }\n"
"QPushButton:checked {\n"
"    color: rgb(255, 255, 255);\n"
"            }")
        self.translate_tab.setObjectName("translate_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.translate_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.input_text_box = QtWidgets.QTextEdit(self.translate_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_text_box.sizePolicy().hasHeightForWidth())
        self.input_text_box.setSizePolicy(sizePolicy)
        self.input_text_box.setMinimumSize(QtCore.QSize(823, 271))
        self.input_text_box.setObjectName("input_text_box")
        self.horizontalLayout_4.addWidget(self.input_text_box)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.import_image = QtWidgets.QPushButton(self.translate_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.import_image.sizePolicy().hasHeightForWidth())
        self.import_image.setSizePolicy(sizePolicy)
        self.import_image.setMinimumSize(QtCore.QSize(40, 40))
        self.import_image.setStyleSheet("QPushButton{\n"
"    border-radius:4%;\n"
"}\n"
"QPushButton:hover{\n"
"    border:2px solid;\n"
"    background-color: rgb(255, 255, 255,0.5);\n"
"    border-color: rgb(29, 150, 213);\n"
"}")
        self.import_image.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-add-image-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.import_image.setIcon(icon)
        self.import_image.setIconSize(QtCore.QSize(35, 35))
        self.import_image.setObjectName("import_image")
        self.verticalLayout_5.addWidget(self.import_image)
        self.import_file = QtWidgets.QPushButton(self.translate_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.import_file.sizePolicy().hasHeightForWidth())
        self.import_file.setSizePolicy(sizePolicy)
        self.import_file.setMinimumSize(QtCore.QSize(40, 40))
        self.import_file.setStyleSheet("QPushButton{\n"
"    border-radius:4%;\n"
"}\n"
"QPushButton:hover{\n"
"    border:2px solid;\n"
"    background-color: rgb(255, 255, 255,0.5);\n"
"    border-color: rgb(29, 150, 213);\n"
"}")
        self.import_file.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-add-file-64 (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.import_file.setIcon(icon1)
        self.import_file.setIconSize(QtCore.QSize(35, 35))
        self.import_file.setObjectName("import_file")
        self.verticalLayout_5.addWidget(self.import_file)
        self.import_pdf = QtWidgets.QPushButton(self.translate_tab)
        self.import_pdf.setMinimumSize(QtCore.QSize(40, 40))
        self.import_pdf.setStyleSheet("QPushButton{\n"
"    border-radius:4%;\n"
"}\n"
"QPushButton:hover{\n"
"    border:2px solid;\n"
"    background-color: rgb(255, 255, 255,0.5);\n"
"    border-color: rgb(29, 150, 213);\n"
"}")
        self.import_pdf.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/download (42).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.import_pdf.setIcon(icon2)
        self.import_pdf.setIconSize(QtCore.QSize(35, 35))
        self.import_pdf.setObjectName("import_pdf")
        self.verticalLayout_5.addWidget(self.import_pdf)
        self.openurl = QtWidgets.QPushButton(self.translate_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openurl.sizePolicy().hasHeightForWidth())
        self.openurl.setSizePolicy(sizePolicy)
        self.openurl.setMinimumSize(QtCore.QSize(40, 40))
        self.openurl.setStyleSheet("QPushButton{\n"
"    border-radius:4%;\n"
"}\n"
"QPushButton:hover{\n"
"    border:2px solid;\n"
"    background-color: rgb(255, 255, 255,0.5);\n"
"    border-color: rgb(29, 150, 213);\n"
"}")
        self.openurl.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-website-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openurl.setIcon(icon3)
        self.openurl.setIconSize(QtCore.QSize(35, 35))
        self.openurl.setObjectName("openurl")
        self.verticalLayout_5.addWidget(self.openurl)
        self.voiceinput = QtWidgets.QPushButton(self.translate_tab)
        self.voiceinput.setMinimumSize(QtCore.QSize(40, 40))
        self.voiceinput.setStyleSheet("QPushButton{\n"
"    border-radius:4%;\n"
"}\n"
"QPushButton:hover{\n"
"    border:2px solid;\n"
"    background-color: rgb(255, 255, 255,0.5);\n"
"    border-color: rgb(29, 150, 213);\n"
"}")
        self.voiceinput.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-microphone-80.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.voiceinput.setIcon(icon4)
        self.voiceinput.setIconSize(QtCore.QSize(35, 35))
        self.voiceinput.setObjectName("voiceinput")
        self.verticalLayout_5.addWidget(self.voiceinput)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 43, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 0, 2, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 34, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 3, 2, 2, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.translate_show = QtWidgets.QTextBrowser(self.translate_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translate_show.sizePolicy().hasHeightForWidth())
        self.translate_show.setSizePolicy(sizePolicy)
        self.translate_show.setMinimumSize(QtCore.QSize(823, 271))
        self.translate_show.setPlaceholderText("")
        self.translate_show.setObjectName("translate_show")
        self.horizontalLayout_5.addWidget(self.translate_show)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.saytranslated = QtWidgets.QPushButton(self.translate_tab)
        self.saytranslated.setMinimumSize(QtCore.QSize(40, 40))
        self.saytranslated.setStyleSheet("QPushButton{\n"
"    border-radius:4%;\n"
"}\n"
"QPushButton:hover{\n"
"    border:2px solid;\n"
"    background-color: rgb(255, 255, 255,0.5);\n"
"    border-color: rgb(29, 150, 213);\n"
"}")
        self.saytranslated.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-speaker-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saytranslated.setIcon(icon5)
        self.saytranslated.setIconSize(QtCore.QSize(40, 40))
        self.saytranslated.setObjectName("saytranslated")
        self.verticalLayout_4.addWidget(self.saytranslated)
        self.starred = QtWidgets.QPushButton(self.translate_tab)
        self.starred.setMinimumSize(QtCore.QSize(40, 40))
        self.starred.setStyleSheet("QPushButton{\n"
"    border-radius:4%;\n"
"}\n"
"QPushButton:hover{\n"
"    border:2px solid;\n"
"    background-color: rgb(255, 255, 255,0.5);\n"
"    border-color: rgb(29, 150, 213);\n"
"}")
        self.starred.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-star-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.starred.setIcon(icon6)
        self.starred.setIconSize(QtCore.QSize(40, 40))
        self.starred.setObjectName("starred")
        self.verticalLayout_4.addWidget(self.starred)
        self.synonym = QtWidgets.QPushButton(self.translate_tab)
        self.synonym.setMinimumSize(QtCore.QSize(40, 40))
        self.synonym.setStyleSheet("QPushButton{\n"
"    border-radius:4%;\n"
"}\n"
"QPushButton:hover{\n"
"    border:2px solid;\n"
"    background-color: rgb(255, 255, 255,0.5);\n"
"    border-color: rgb(29, 150, 213);\n"
"}")
        self.synonym.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-group-96 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.synonym.setIcon(icon7)
        self.synonym.setIconSize(QtCore.QSize(40, 40))
        self.synonym.setObjectName("synonym")
        self.verticalLayout_4.addWidget(self.synonym)
        self.cleartext = QtWidgets.QPushButton(self.translate_tab)
        self.cleartext.setMinimumSize(QtCore.QSize(40, 40))
        self.cleartext.setStyleSheet("QPushButton{\n"
"    border-radius:4%;\n"
"}\n"
"QPushButton:hover{\n"
"    border:2px solid;\n"
"    background-color: rgb(255, 255, 255,0.5);\n"
"    border-color: rgb(29, 150, 213);\n"
"}")
        self.cleartext.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-clear-symbol-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cleartext.setIcon(icon8)
        self.cleartext.setIconSize(QtCore.QSize(40, 40))
        self.cleartext.setObjectName("cleartext")
        self.verticalLayout_4.addWidget(self.cleartext)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 4, 0, 2, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.exportpdf = QtWidgets.QPushButton(self.translate_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportpdf.sizePolicy().hasHeightForWidth())
        self.exportpdf.setSizePolicy(sizePolicy)
        self.exportpdf.setMinimumSize(QtCore.QSize(138, 71))
        font = QtGui.QFont()
        font.setFamily("B Zar")
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.exportpdf.setFont(font)
        self.exportpdf.setStyleSheet("/* CSS */\n"
"QPushButton:hover {\n"
"    background-color:rgb(246, 97, 81);\n"
"    font-size:15px;\n"
"    border-radius:15%;\n"
"}")
        self.exportpdf.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-pdf-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exportpdf.setIcon(icon9)
        self.exportpdf.setIconSize(QtCore.QSize(30, 30))
        self.exportpdf.setObjectName("exportpdf")
        self.horizontalLayout_3.addWidget(self.exportpdf)
        self.exporttxt = QtWidgets.QPushButton(self.translate_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exporttxt.sizePolicy().hasHeightForWidth())
        self.exporttxt.setSizePolicy(sizePolicy)
        self.exporttxt.setMinimumSize(QtCore.QSize(137, 71))
        font = QtGui.QFont()
        font.setFamily("B Zar")
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.exporttxt.setFont(font)
        self.exporttxt.setStyleSheet("/* CSS */\n"
"QPushButton:hover {\n"
"    background-color: rgb(220, 138, 221);\n"
"    font-size:15px;\n"
"    border-radius:15%;\n"
"}")
        self.exporttxt.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-txt-96 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exporttxt.setIcon(icon10)
        self.exporttxt.setIconSize(QtCore.QSize(30, 30))
        self.exporttxt.setObjectName("exporttxt")
        self.horizontalLayout_3.addWidget(self.exporttxt)
        self.exportword = QtWidgets.QPushButton(self.translate_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportword.sizePolicy().hasHeightForWidth())
        self.exportword.setSizePolicy(sizePolicy)
        self.exportword.setMinimumSize(QtCore.QSize(137, 71))
        font = QtGui.QFont()
        font.setFamily("B Zar")
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.exportword.setFont(font)
        self.exportword.setStyleSheet("/* CSS */\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 179, 237);\n"
"    font-size:15px;\n"
"    border-radius:15%;\n"
"    icon-size: 48px 48px;\n"
"}")
        self.exportword.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-word-file-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exportword.setIcon(icon11)
        self.exportword.setIconSize(QtCore.QSize(30, 30))
        self.exportword.setObjectName("exportword")
        self.horizontalLayout_3.addWidget(self.exportword)
        self.addtofavorite = QtWidgets.QPushButton(self.translate_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addtofavorite.sizePolicy().hasHeightForWidth())
        self.addtofavorite.setSizePolicy(sizePolicy)
        self.addtofavorite.setMinimumSize(QtCore.QSize(137, 71))
        font = QtGui.QFont()
        font.setFamily("B Zar")
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.addtofavorite.setFont(font)
        self.addtofavorite.setStyleSheet("/* CSS */\n"
"QPushButton:hover {\n"
"    background-color: rgb(106, 192, 4);\n"
"    font-size:20px;\n"
"    border-radius:15%;\n"
"}")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-bookmark-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addtofavorite.setIcon(icon12)
        self.addtofavorite.setIconSize(QtCore.QSize(33, 33))
        self.addtofavorite.setObjectName("addtofavorite")
        self.horizontalLayout_3.addWidget(self.addtofavorite)
        self.edit = QtWidgets.QPushButton(self.translate_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit.sizePolicy().hasHeightForWidth())
        self.edit.setSizePolicy(sizePolicy)
        self.edit.setMinimumSize(QtCore.QSize(137, 71))
        font = QtGui.QFont()
        font.setFamily("B Zar")
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.edit.setFont(font)
        self.edit.setStyleSheet("/* CSS */\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 177, 55);\n"
"    font-size:20px;\n"
"    border-radius:15%;\n"
"}")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-edit-96 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit.setIcon(icon13)
        self.edit.setIconSize(QtCore.QSize(30, 30))
        self.edit.setObjectName("edit")
        self.horizontalLayout_3.addWidget(self.edit)
        self.copy = QtWidgets.QPushButton(self.translate_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copy.sizePolicy().hasHeightForWidth())
        self.copy.setSizePolicy(sizePolicy)
        self.copy.setMinimumSize(QtCore.QSize(138, 71))
        font = QtGui.QFont()
        font.setFamily("B Zar")
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.copy.setFont(font)
        self.copy.setStyleSheet("/* CSS */\n"
"QPushButton:hover {\n"
"    background-color: rgb(222, 221, 218);\n"
"    font-size:20px;\n"
"    border-radius:15%;\n"
"}")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-copy-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copy.setIcon(icon14)
        self.copy.setIconSize(QtCore.QSize(30, 30))
        self.copy.setObjectName("copy")
        self.horizontalLayout_3.addWidget(self.copy)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 6, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(351, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 6, 1, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.first_language_down = QtWidgets.QPushButton(self.translate_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.first_language_down.sizePolicy().hasHeightForWidth())
        self.first_language_down.setSizePolicy(sizePolicy)
        self.first_language_down.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.first_language_down.setFont(font)
        self.first_language_down.setStyleSheet("QPushButton:checked { \n"
"    color: rgb(29, 150, 213);"
"    border: none; /* حذف حاشیه پیش‌فرض */"
"    border-bottom: 2px solid rgb(29, 150, 213);"
"            }\n"
"")
        self.first_language_down.setCheckable(True)
        self.first_language_down.setChecked(False)
        self.first_language_down.setAutoExclusive(True)
        self.first_language_down.setObjectName("first_language_down")
        self.horizontalLayout.addWidget(self.first_language_down)
        self.second_language_down = QtWidgets.QPushButton(self.translate_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.second_language_down.sizePolicy().hasHeightForWidth())
        self.second_language_down.setStyleSheet("QPushButton:checked { \n"
"    color: rgb(29, 150, 213);"
"    border: none; /* حذف حاشیه پیش‌فرض */"
"    border-bottom: 2px solid rgb(29, 150, 213);"
"            }\n"
"")
        self.second_language_down.setSizePolicy(sizePolicy)
        self.second_language_down.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.second_language_down.setFont(font)
        self.second_language_down.setCheckable(True)
        self.second_language_down.setAutoExclusive(True)
        self.second_language_down.setObjectName("second_language_down")
        self.horizontalLayout.addWidget(self.second_language_down)
        self.third_language_down = QtWidgets.QPushButton(self.translate_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.third_language_down.sizePolicy().hasHeightForWidth())
        self.third_language_down.setSizePolicy(sizePolicy)
        self.third_language_down.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.third_language_down.setFont(font)
        self.third_language_down.setStyleSheet("QPushButton:checked { \n"
"    color: rgb(29, 150, 213);"
"    border: none; /* حذف حاشیه پیش‌فرض */"
"    border-bottom: 2px solid rgb(29, 150, 213);"
"            }\n"
"")
        self.third_language_down.setCheckable(True)
        self.third_language_down.setChecked(False)
        self.third_language_down.setAutoExclusive(True)
        self.third_language_down.setObjectName("third_language_down")
        self.horizontalLayout.addWidget(self.third_language_down)
        self.collapse_down = QtWidgets.QPushButton(self.translate_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.collapse_down.sizePolicy().hasHeightForWidth())
        self.collapse_down.setSizePolicy(sizePolicy)
        self.collapse_down.setMinimumSize(QtCore.QSize(0, 18))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.collapse_down.setFont(font)
        self.collapse_down.setStyleSheet("QPushButton {\n"
"                background-color:rgb(255, 255, 255,0.0);\n"
"                color: rgb(94, 92, 100); \n"
"                border: none;\n"
"                  border-radius:0px;\n"
"                text-align: center;\n"
"                text-decoration: none;\n"
"                transition-duration: 0.4s;\n"
"                cursor: pointer;\n"
"            }\n"
"QPushButton:hover {\n"
"                background-color: rgb(192, 191, 188, 0.3);\n"
"                color: white;\n"
"                     animation: shake 0.82s cubic-bezier(.36,.07,.19,.97) both;\n"
"                   transform: translate3d(0, 0, 0);\n"
"                  backface-visibility: hidden;\n"
"                perspective: 1000px;\n"
"            }\n"
"")
        self.collapse_down.setText("")
        self.collapse_down.angle = 0
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-expand-arrow-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.collapse_down.setIcon(icon15)
        self.collapse_down.setObjectName("collapse_down")
        self.horizontalLayout.addWidget(self.collapse_down)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.bottom_table = QtWidgets.QTableWidget(self.translate_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottom_table.sizePolicy().hasHeightForWidth())
        self.bottom_table.setSizePolicy(sizePolicy)
        self.bottom_table.setMinimumSize(QtCore.QSize(316, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Serif CJK TC")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.bottom_table.setFont(font)
        self.bottom_table.setMouseTracking(True)
        self.bottom_table.setTabletTracking(True)
        self.bottom_table.setStyleSheet("QHeaderView::section { \n"
"                background-color: none; \n"
"                color: none; \n"
"                border: none; \n"
"                height: 0px;\n"
"                width: 0px;\n"
"            }\n"
"QTableWidget::item:hover {\n"
"                background-color: #d3d3d3; /* رنگ پس‌زمینه هنگام هاور */\n"
"                 font-size: 19.2px;\n"
"            }\n"
"")
        self.bottom_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.bottom_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.bottom_table.setAutoScroll(False)
        self.bottom_table.setAutoScrollMargin(16)
        self.bottom_table.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.SelectedClicked)
        self.bottom_table.setTabKeyNavigation(True)
        self.bottom_table.setTextElideMode(QtCore.Qt.ElideLeft)
        self.bottom_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.bottom_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.bottom_table.setShowGrid(False)
        self.bottom_table.setGridStyle(QtCore.Qt.NoPen)
        self.bottom_table.setObjectName("bottom_table")
        self.bottom_table.setColumnCount(3)
        self.bottom_table.setRowCount(6)
        self.bottom_table.setVisible(False)
        item = QtWidgets.QTableWidgetItem()
        self.bottom_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bottom_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.bottom_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.bottom_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.bottom_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.bottom_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.bottom_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bottom_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.bottom_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/flags/united kingdom-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon16)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate)
        self.bottom_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/flags/iran-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon17)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.bottom_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/flags/italy-64 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon18)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.bottom_table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/flags/netherlands-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon19)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.bottom_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/flags/china-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon20)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.bottom_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/flags/portugal-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon21)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.bottom_table.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/flags/france-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon22)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.bottom_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/flags/japan.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon23)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.bottom_table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/flags/india-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon24)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.bottom_table.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/flags/iraq.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon25)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.bottom_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/flags/germany-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon26)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.bottom_table.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/flags/turkey-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon27)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.bottom_table.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/flags/spain-64 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon28)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.bottom_table.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/flags/czech republic-64 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon29)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.bottom_table.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/flags/sweden-64 (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon30)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.bottom_table.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/flags/russia-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon31)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.bottom_table.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(":/flags/pakistan-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon32)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.bottom_table.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(":/flags/south korea-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon33)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.bottom_table.setItem(5, 2, item)
        self.bottom_table.horizontalHeader().setVisible(True)
        self.bottom_table.horizontalHeader().setCascadingSectionResizes(False)
        self.bottom_table.horizontalHeader().setSortIndicatorShown(False)
        self.verticalLayout.addWidget(self.bottom_table)
        spacerItem4 = QtWidgets.QSpacerItem(20, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.translate = QtWidgets.QPushButton(self.translate_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translate.sizePolicy().hasHeightForWidth())
        self.translate.setSizePolicy(sizePolicy)
        self.translate.setMinimumSize(QtCore.QSize(316, 2))
        self.translate.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(23)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.translate.setFont(font)
        self.translate.setStyleSheet("\n"
"/* CSS */\n"
"QPushButton {\n"
"  align-items: center;\n"
"  background-clip: padding-box;\n"
"  background-color: rgb(5, 134, 176);\n"
"  border: 1px solid transparent;\n"
"  border-radius: 3px;\n"
"  box-shadow: rgba(0, 0, 0, 0.02) 0 1px 3px 0;\n"
"  box-sizing: border-box;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  display: inline-flex;\n"
"  font-weight: 600;\n"
"  justify-content: center;\n"
"  line-height: 1.25;\n"
"  margin: 0;\n"
"  min-height: 3rem;\n"
"  padding: calc(.875rem - 1px) calc(1.5rem - 1px);\n"
"  position: relative;\n"
"  text-decoration: none;\n"
"  transition: all 250ms;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"  vertical-align: baseline;\n"
"  width: auto;\n"
"border-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* CSS */\n"
"QPushButton:hover {\n"
"    background-color: rgb(36, 174, 254);\n"
"    font-size:31px;\n"
"    \n"
"}")
        self.translate.setObjectName("translate")
        self.verticalLayout.addWidget(self.translate)
        self.gridLayout_2.addLayout(self.verticalLayout, 5, 2, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Detected_language_button = QtWidgets.QPushButton(self.translate_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Detected_language_button.sizePolicy().hasHeightForWidth())
        self.Detected_language_button.setSizePolicy(sizePolicy)
        self.Detected_language_button.setMinimumSize(QtCore.QSize(149, 0))
        self.Detected_language_button.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Detected_language_button.setFont(font)
        self.Detected_language_button.setStyleSheet("QPushButton {\n"
"                background-color:rgb(255, 255, 255,0.0);\n"
"                color: rgb(94, 92, 100); \n"
"                border: none;\n"
"                  border-radius:0px;\n"
"                text-align: center;\n"
"                text-decoration: none;\n"
"                transition-duration: 0.4s;\n"
"                cursor: pointer;\n"
"            }\n"
"            QPushButton:hover {\n"
"                  \n"
"                  color: rgb(0, 0, 0);\n"
"                background-color: rgb(192, 191, 188, 0.3);\n"
"                  font-size: 14px;\n"
"            }\n"
"QPushButton:checked {\n"
"    color: rgb(29, 150, 213);"
"    border: none; /* حذف حاشیه پیش‌فرض */"
"    border-bottom: 2px solid rgb(29, 150, 213);"
"            }")
        self.Detected_language_button.setCheckable(True)
        self.Detected_language_button.setAutoExclusive(False)
        self.Detected_language_button.setObjectName("Detected_language_button")
        self.horizontalLayout_2.addWidget(self.Detected_language_button)
        self.first_language_top = QtWidgets.QPushButton(self.translate_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.first_language_top.sizePolicy().hasHeightForWidth())
        self.first_language_top.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.first_language_top.setFont(font)
        self.first_language_top.setStyleSheet("QPushButton {\n"
"                background-color:rgb(255, 255, 255,0.0);\n"
"                color: rgb(94, 92, 100); \n"
"                border: none;\n"
"                  border-radius:0px;\n"
"                text-align: center;\n"
"                text-decoration: none;\n"
"                transition-duration: 0.4s;\n"
"                cursor: pointer;\n"
"            }\n"
"            QPushButton:hover {\n"
"                  \n"
"                  color: rgb(0, 0, 0);\n"
"                background-color: rgb(192, 191, 188, 0.3);\n"
"                  font-size: 14px;\n"
"            }\n"
"QPushButton:checked {\n"
"    color: rgb(29, 150, 213);"
"    border: none; /* حذف حاشیه پیش‌فرض */"
"    border-bottom: 2px solid rgb(29, 150, 213);"
"            }")
        self.first_language_top.setCheckable(True)
        self.first_language_top.setAutoExclusive(False)
        self.first_language_top.setObjectName("first_language_top")
        self.horizontalLayout_2.addWidget(self.first_language_top)
        self.collapse_top = QtWidgets.QPushButton(self.translate_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.collapse_top.sizePolicy().hasHeightForWidth())
        self.collapse_top.setSizePolicy(sizePolicy)
        self.collapse_top.setMinimumSize(QtCore.QSize(0, 18))
        self.collapse_top.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.collapse_top.setFont(font)
        self.collapse_top.setStyleSheet("QPushButton {\n"
"                background-color:rgb(255, 255, 255,0.0);\n"
"                color: rgb(94, 92, 100); \n"
"                text-align: center;\n"
"                transition-duration: 0.4s;\n"
"                cursor: pointer;\n"
"            }\n"
"QPushButton:hover {\n"
"                background-color: rgb(192, 191, 188, 0.3);\n"
"            }\n"
"")
        self.collapse_top.setText("")
        self.collapse_top.angle = 0
        self.collapse_top.setIcon(icon15)
        self.collapse_top.setObjectName("collapse_top")
        self.horizontalLayout_2.addWidget(self.collapse_top)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.top_table = QtWidgets.QTableWidget(self.translate_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_table.sizePolicy().hasHeightForWidth())
        self.top_table.setSizePolicy(sizePolicy)
        self.top_table.setMinimumSize(QtCore.QSize(316, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Serif CJK TC")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.top_table.setFont(font)
        self.top_table.setMouseTracking(True)
        self.top_table.setTabletTracking(True)
        self.top_table.setAcceptDrops(False)
        self.top_table.setStyleSheet("QHeaderView::section { \n"
"                background-color: none; \n"
"                color: none; \n"
"                border: none; \n"
"                height: 0px;\n"
"                width: 0px;\n"
"            }\n"
"QTableWidget::item:hover {\n"
"                background-color: #d3d3d3; /* رنگ پس‌زمینه هنگام هاور */\n"
"                  font-size:11px;\n"
"            }")
        self.top_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.top_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.top_table.setAutoScroll(False)
        self.top_table.setAutoScrollMargin(16)
        self.top_table.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.SelectedClicked)
        self.top_table.setVisible(False)
        self.top_table.setTabKeyNavigation(True)
        self.top_table.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.top_table.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.top_table.setTextElideMode(QtCore.Qt.ElideLeft)
        self.top_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.top_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.top_table.setShowGrid(False)
        self.top_table.setGridStyle(QtCore.Qt.NoPen)
        self.top_table.setObjectName("top_table")
        self.top_table.setColumnCount(3)
        self.top_table.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.top_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.top_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.top_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.top_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.top_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.top_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.top_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.top_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.top_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        item.setIcon(icon16)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.top_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setIcon(icon17)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.top_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setIcon(icon18)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.top_table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setIcon(icon19)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.top_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setIcon(icon20)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.top_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setIcon(icon21)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.top_table.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setIcon(icon22)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.top_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setIcon(icon23)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.top_table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setIcon(icon24)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.top_table.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setIcon(icon25)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.top_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setIcon(icon26)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.top_table.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setIcon(icon27)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.top_table.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(":/flags/spain-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon34)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.top_table.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setIcon(icon29)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.top_table.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setIcon(icon30)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.top_table.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setIcon(icon31)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.top_table.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setIcon(icon32)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.top_table.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setIcon(icon33)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.top_table.setItem(5, 2, item)
        self.top_table.horizontalHeader().setVisible(True)
        self.top_table.horizontalHeader().setCascadingSectionResizes(False)
        self.top_table.horizontalHeader().setSortIndicatorShown(False)
        self.verticalLayout_2.addWidget(self.top_table)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.reverse_button = QtWidgets.QPushButton(self.translate_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reverse_button.sizePolicy().hasHeightForWidth())
        self.reverse_button.setSizePolicy(sizePolicy)
        self.reverse_button.setMinimumSize(QtCore.QSize(30, 30))
        self.reverse_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.reverse_button.setStyleSheet("QPushButton:hover{\n"
"    border-radius:15px;\n"
"    background-color: rgb(222, 221, 218);\n"
"}\n"
"\n"
"")
        self.reverse_button.setText("")
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-sorting-arrows-horizontal-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reverse_button.setIcon(icon35)
        self.reverse_button.setIconSize(QtCore.QSize(25, 25))
        self.reverse_button.setObjectName("reverse_button")
        self.verticalLayout_3.addWidget(self.reverse_button, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 1, 2, 2, 1)
        self.tabWidget.addTab(self.translate_tab, "")
        self.favorite_tab = QtWidgets.QWidget()
        self.favorite_tab.setStyleSheet("QPushButton{\n"
"    border-radius:17px;\n"
"    border: 3px solid #4CAF50;\n"
"    border-color: rgb(29, 150, 213);\n"
"    background-color:transparent;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(26, 241, 255, 0.5);\n"
"    border: 4px solid rgb(29, 150, 213)\n"
"}")
        self.favorite_tab.setObjectName("favorite_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.favorite_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(40, -1, 40, 0)
        self.gridLayout.setHorizontalSpacing(60)
        self.gridLayout.setVerticalSpacing(87)
        self.gridLayout.setObjectName("gridLayout")
        self.favoritcase1 = QtWidgets.QPushButton(self.favorite_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.favoritcase1.sizePolicy().hasHeightForWidth())
        self.favoritcase1.setSizePolicy(sizePolicy)
        self.favoritcase1.setMinimumSize(QtCore.QSize(0, 120))
        font = QtGui.QFont()
        font.setPointSize(63)
        self.favoritcase1.setFont(font)
        self.favoritcase1.setText("")
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-add-64 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.favoritcase1.setIcon(icon36)
        self.favoritcase1.setIconSize(QtCore.QSize(60, 60))
        self.favoritcase1.setObjectName("favoritcase1")
        self.gridLayout.addWidget(self.favoritcase1, 0, 0, 1, 1)
        self.favoritcase2 = QtWidgets.QPushButton(self.favorite_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.favoritcase2.sizePolicy().hasHeightForWidth())
        self.favoritcase2.setSizePolicy(sizePolicy)
        self.favoritcase2.setMinimumSize(QtCore.QSize(0, 120))
        self.favoritcase2.setText("")
        self.favoritcase2.setIcon(icon36)
        self.favoritcase2.setIconSize(QtCore.QSize(60, 60))
        self.favoritcase2.setObjectName("favoritcase2")
        self.gridLayout.addWidget(self.favoritcase2, 0, 1, 1, 1)
        self.favoritcase3 = QtWidgets.QPushButton(self.favorite_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.favoritcase3.sizePolicy().hasHeightForWidth())
        self.favoritcase3.setSizePolicy(sizePolicy)
        self.favoritcase3.setMinimumSize(QtCore.QSize(0, 120))
        self.favoritcase3.setText("")
        self.favoritcase3.setIcon(icon36)
        self.favoritcase3.setIconSize(QtCore.QSize(60, 60))
        self.favoritcase3.setObjectName("favoritcase3")
        self.gridLayout.addWidget(self.favoritcase3, 0, 2, 1, 1)
        self.favoritcase4 = QtWidgets.QPushButton(self.favorite_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.favoritcase4.sizePolicy().hasHeightForWidth())
        self.favoritcase4.setSizePolicy(sizePolicy)
        self.favoritcase4.setMinimumSize(QtCore.QSize(0, 120))
        self.favoritcase4.setText("")
        self.favoritcase4.setIcon(icon36)
        self.favoritcase4.setIconSize(QtCore.QSize(60, 60))
        self.favoritcase4.setObjectName("favoritcase4")
        self.gridLayout.addWidget(self.favoritcase4, 1, 0, 1, 1)
        self.favoritcase5 = QtWidgets.QPushButton(self.favorite_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.favoritcase5.sizePolicy().hasHeightForWidth())
        self.favoritcase5.setSizePolicy(sizePolicy)
        self.favoritcase5.setMinimumSize(QtCore.QSize(0, 120))
        self.favoritcase5.setText("")
        self.favoritcase5.setIcon(icon36)
        self.favoritcase5.setIconSize(QtCore.QSize(60, 60))
        self.favoritcase5.setObjectName("favoritcase5")
        self.gridLayout.addWidget(self.favoritcase5, 1, 1, 1, 1)
        self.favoritcase6 = QtWidgets.QPushButton(self.favorite_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.favoritcase6.sizePolicy().hasHeightForWidth())
        self.favoritcase6.setSizePolicy(sizePolicy)
        self.favoritcase6.setMinimumSize(QtCore.QSize(0, 120))
        self.favoritcase6.setText("")
        self.favoritcase6.setIcon(icon36)
        self.favoritcase6.setIconSize(QtCore.QSize(60, 60))
        self.favoritcase6.setObjectName("favoritcase6")
        self.gridLayout.addWidget(self.favoritcase6, 1, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap("Downloads/icons8-bookmark-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.favorite_tab, icon37, "")
        self.flash_cart_tab = QtWidgets.QWidget()
        self.flash_cart_tab.setObjectName("flash_cart_tab")
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap("Downloads/icons/3813681.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.flash_cart_tab, icon38, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.history_tab = QtWidgets.QWidget()
        self.history_tab.setObjectName("history_tab")
        self.tabWidget.addTab(self.history_tab, "")
        self.setting_tab = QtWidgets.QWidget()
        self.setting_tab.setObjectName("setting_tab")
        self.tabWidget.addTab(self.setting_tab, "")
        self.about_tab = QtWidgets.QWidget()
        self.about_tab.setObjectName("about_tab")
        self.tabWidget.addTab(self.about_tab, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)


        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)


        self.collapse_top.clicked.connect(self.toggle_top_table_visibility) # type: ignore
        self.cleartext.clicked.connect(self.translate_show.clear) # type: ignore
        self.bottom_table.itemClicked['QTableWidgetItem*'].connect(self.third_language_down.update) # type: ignore
        self.collapse_down.clicked.connect(self.toggle_down_table_visibility) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        # اتصال سیگنال کلیک جدول به تابع
        self.top_table.cellClicked.connect(self.select_source_language)
        self.bottom_table.cellClicked.connect(self.select_target_language)
        #انتخاب یکی از دو حالت برای زبان مرجع
        self.first_language_top.clicked.connect(self.toggle_button_first_top)
        self.Detected_language_button.clicked.connect(self.toggle_button_detected)
        self.reverse_button.clicked.connect(self.reverse_language)
        self.first_language_down.clicked.connect(self.update_selected_la_dict)
        self.second_language_down.clicked.connect(self.update_selected_la_dict)
        self.third_language_down.clicked.connect(self.update_selected_la_dict)
        #انتخاب عکس و استخراج متن
        # self.import_image.clicked.connect(self.read_image_and_update_text)
        self.import_file.clicked.connect(self.extract_text_from_file)
        self.import_pdf.clicked.connect(self.import_and_read_pdf_file)
        self.openurl.clicked.connect(self.open_and_translate)
        #زبان‌های انتخاب شده برای ترجمه
        self.selected_languages = {"source": "", "target": ""}
        self.languages_convert = {
                    "english": "eng",
                    "arabic": "ara",
                    "french": "fra",
                    "german": "deu",
                    "spanish": "spa",
                    "russian": "rus",
                    "chinese": "chi_sim",  # Simplified Chinese
                    "japanese": "jpn",
                    "korean": "kor",
                    "italian": "ita",
                    "portuguese": "por",
                    "dutch": "nld",
                    "turkish": "tur",
                    "hindi": "hin",
                    "urdu": "urd",
                    "swedish": "swe",
                    "persian": "fas",
                    "czech": "ces"
            }



        # functions
    #انتخاب زبان هدف
    def select_target_language(self,  row, column):
            selected_language = self.bottom_table.item(row, column).text()
            self.bottom_table.hide()
            if selected_language.lower() not in [self.second_language_down.text(), self.third_language_down.text(), self.first_language_down.text()]:
                    sbt = self.second_language_down.text()
                    self.second_language_down.setText(self.first_language_down.text())
                    self.third_language_down.setText(sbt)
                    self.first_language_down.setText(selected_language.lower())
                    self.first_language_down.setChecked(True)
                    self.selected_languages["target"] = self.first_language_down.text()
                    self.collapse_down.setIcon(QIcon(':/newPrefix/icons8-expand-arrow-64.png'))


    def open_file_dialog(self, filetypes=[('PDF files', "*.pdf")]):
            file_path = filedialog.askopenfilename(filetypes= filetypes)
            if file_path:
                    return file_path

    #انتخاب زبان مرجع
    def select_source_language(self, row, column):
            selected_language = self.top_table.item(row, column).text()
            self.top_table.hide()
            self.first_language_top.setText(selected_language)
            self.collapse_top.setIcon(QIcon(':/newPrefix/icons8-expand-arrow-64.png'))


    # پنهان کردن جدول زبان‌های بالایی
    def toggle_top_table_visibility(self):
            if self.top_table.isVisible():
                    self.top_table.hide()  # پنهان کردن جدول
                    sleep(0.10)
                    self.collapse_top.setIcon(QIcon(':/newPrefix/icons8-expand-arrow-64.png'))
            else:
                    self.top_table.show()  # ظاهر کردن جدول
                    sleep(0.10)
                    self.collapse_top.setIcon(QIcon(':/newPrefix/icons8-collapse-arrow-64.png'))


                    # پنهان کردن جدول زبان‌های پایینی
    def toggle_down_table_visibility(self):
            if self.bottom_table.isVisible():
                    self.bottom_table.hide()  # پنهان کردن جدول
                    sleep(0.10)
                    self.collapse_down.setIcon(QIcon(':/newPrefix/icons8-expand-arrow-64.png'))
            else:
                    self.bottom_table.show()  # ظاهر کردن جدول
                    sleep(0.10)
                    self.collapse_down.setIcon(QIcon(':/newPrefix/icons8-collapse-arrow-64.png'))

    #تغییر وضعیت متناوب فعال بودن دکمه‌های زبان بالایی
    def toggle_button_first_top(self):
            self.Detected_language_button.setChecked(False)
            self.first_language_top.setChecked(True)
            self.selected_languages["source"] = self.first_language_top.text()
            print(self.selected_languages)

    def toggle_button_detected(self):
            self.Detected_language_button.setChecked(True)
            self.first_language_top.setChecked(False)

    def reverse_language(self):
            #در صورتی که دکمه تشخیص زبان خودکار فعال نیست
            if not self.Detected_language_button.isChecked():
                    result = ""
                    if self.first_language_down.isChecked():
                            result = self.first_language_down
                    elif self.second_language_down.isChecked():
                            result = self.second_language_down
                    elif self.third_language_down.isChecked():
                            result = self.third_language_down
                    if result != "":
                            i = result.text()
                            result.setText(self.first_language_top.text())
                            self.first_language_top.setText(i)
                            self.selected_languages["target"], self.selected_languages["source"] = \
                                    self.selected_languages["source"], self.selected_languages["target"]

    #بروزرسانی زبان هدف
    def update_selected_la_dict(self):
            if self.first_language_down.isChecked():
                    self.selected_languages["target"] = self.first_language_down.text()
            elif self.second_language_down.isChecked():
                    self.selected_languages["target"] = self.second_language_down
            elif self.third_language_down.isChecked():
                    self.selected_languages["target"] = self.third_language_down


    #بروزرسانی متن ترجمه
    def read_image_and_update_text(self):
            newtext = self.select_image_and_read()
            self.input_text_box.setText(newtext)
    #انتخاب عکس و استخراج متن
    def select_image_and_read(self):
            languages = {
                    "english": "eng",
                    "arabic": "ara",
                    "french": "fra",
                    "german": "deu",
                    "spanish": "spa",
                    "russian": "rus",
                    "chinese": "chi_sim",  # Simplified Chinese
                    "japanese": "jpn",
                    "korean": "kor",
                    "italian": "ita",
                    "portuguese": "por",
                    "dutch": "nld",
                    "turkish": "tur",
                    "hindi": "hin",
                    "urdu": "urd",
                    "swedish": "swe",
                    "persian": "fas",
                    "czech": "ces"
            }
            # انتخاب فایل تصویر
            image_path = self.open_file_dialog()
            lang_choice = easygui.choicebox("لطفاً زبان متن را انتخاب کنید:", "انتخاب زبان",
                                            list(languages.keys()))
            lang_code = languages[lang_choice]
            # استخراج متن
            img = Image.open(image_path)
            custom_config = r'--oem 3 --psm 6 -l ' + f"{lang_code}"
            text = pytesseract.image_to_string(img, config=custom_config)
            return text

    def show_message_box(self, text, title):
            """تبدیل متن فارسی برای نمایش صحیح از راست به چپ"""
            reshaped_text = arabic_reshaper.reshape(text)
            formatted_message = get_display(reshaped_text)
            formatted_title = get_display(arabic_reshaper.reshape(title))
            easygui.msgbox(formatted_message, formatted_title, ok_button=get_display(arabic_reshaper.reshape("تایید")))


    #استخراج متن از فایل
    def extract_text_from_file(self):
            text_to_translate = ""
            """
            این تابع متن را از فایل‌های Word (.docx) و متنی (.txt) استخراج می‌کند.
            :return: متن استخراج شده از فایل
            """
            #ایجاد پنجره پیام
            file_path = self.open_file_dialog(filetypes=[("text files", "*.docx", "*.doc", "*.txt")])

            # مسیر و پسوند فایل
            file_extension = os.path.splitext(file_path)
            if file_extension[1].lower() in ['.docx',".doc"]:
                    doc = docx.Document(file_path)
                    full_text = []
                    for para in doc.paragraphs:
                            full_text.append(para.text)
                    text_to_translate += '\n'.join(full_text)
            elif file_extension[1].lower() == '.txt':
                    # استخراج متن از فایل متنی
                    with open(file_path, 'r', encoding='utf-8') as file:
                            text_to_translate = file.read()
            else:
                    self.show_message_box("مشکلی متاسفانه رخ داده است", "خطا!")
            if text_to_translate:
                    self.input_text_box.setText(text_to_translate)


    def import_and_read_pdf_file(self):
            pdfText = ""
            # مسیر فایل PDF خود را اینجا قرار دهید
            pdf_path = self.open_file_dialog()
            if pdf_path:
                    # باز کردن فایل PDF
                    pdf_document = fitz.open(pdf_path)
                    # تعداد صفحات PDF را دریافت کنید
                    num_pages = pdf_document.page_count
                    # استخراج متن از هر صفحه
                    for page_num in range(num_pages):
                            page = pdf_document.load_page(page_num)
                            text = page.get_text()
                            pdfText += text
                    self.input_text_box.setText(pdfText)
                    # بستن فایل PDF
                    pdf_document.close()

    def open_and_translate(self,target_language='fa'):
            url = easygui.enterbox("please enter the url ")
            target_language = self.languages_convert[self.selected_languages["target"]]

            if url:
                    # آدرس ترجمه شده توسط Google Translate
                    translate_url = f'https://translate.google.com/translate?sl=auto&tl={target_language}&u={url}'
                    # باز کردن آدرس در یک تب جدید مرورگر پیش‌فرض
                    webbrowser.open_new_tab(translate_url)
            else:
                    easygui.msgbox("                 url error", "error")




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addtofavorite.setToolTip(_translate("MainWindow", "<html><head/><body><p>بلل</p><p><br/></p></body></html>"))
        self.addtofavorite.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>ل</p></body></html>"))
        self.addtofavorite.setText(_translate("MainWindow", "افزودن به "))
        self.edit.setText(_translate("MainWindow", "ویرایش"))
        self.copy.setText(_translate("MainWindow", "کپی"))
        self.first_language_down.setText(_translate("MainWindow", "english"))
        self.second_language_down.setText(_translate("MainWindow", "persian"))
        self.third_language_down.setText(_translate("MainWindow", "arabic"))
        self.bottom_table.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.bottom_table.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.bottom_table.setSortingEnabled(False)
        item = self.bottom_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.bottom_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.bottom_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.bottom_table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.bottom_table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.bottom_table.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.bottom_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.bottom_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.bottom_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column"))
        __sortingEnabled = self.bottom_table.isSortingEnabled()
        self.bottom_table.setSortingEnabled(False)
        item = self.bottom_table.item(0, 0)
        item.setText(_translate("MainWindow", "English"))
        item = self.bottom_table.item(0, 1)
        item.setText(_translate("MainWindow", "Persian"))
        item = self.bottom_table.item(0, 2)
        item.setText(_translate("MainWindow", "Italian"))
        item = self.bottom_table.item(1, 0)
        item.setText(_translate("MainWindow", "Dutch"))
        item = self.bottom_table.item(1, 1)
        item.setText(_translate("MainWindow", "Chinese"))
        item = self.bottom_table.item(1, 2)
        item.setText(_translate("MainWindow", "Portuguese"))
        item = self.bottom_table.item(2, 0)
        item.setText(_translate("MainWindow", "French"))
        item = self.bottom_table.item(2, 1)
        item.setText(_translate("MainWindow", "Japanese"))
        item = self.bottom_table.item(2, 2)
        item.setText(_translate("MainWindow", "Hindi"))
        item = self.bottom_table.item(3, 0)
        item.setText(_translate("MainWindow", "Arabic"))
        item = self.bottom_table.item(3, 1)
        item.setText(_translate("MainWindow", "German"))
        item = self.bottom_table.item(3, 2)
        item.setText(_translate("MainWindow", "Turkish"))
        item = self.bottom_table.item(4, 0)
        item.setText(_translate("MainWindow", "Spanish"))
        item = self.bottom_table.item(4, 1)
        item.setText(_translate("MainWindow", "Czech"))
        item = self.bottom_table.item(4, 2)
        item.setText(_translate("MainWindow", "Swedish"))
        item = self.bottom_table.item(5, 0)
        item.setText(_translate("MainWindow", "Russian"))
        item = self.bottom_table.item(5, 1)
        item.setText(_translate("MainWindow", "Pashto"))
        item = self.bottom_table.item(5, 2)
        item.setText(_translate("MainWindow", "Korean"))
        self.bottom_table.setSortingEnabled(__sortingEnabled)
        self.translate.setText(_translate("MainWindow", "ترجمه"))
        self.Detected_language_button.setText(_translate("MainWindow", "Detected language"))
        self.first_language_top.setText(_translate("MainWindow", "english"))
        self.top_table.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.top_table.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.top_table.setSortingEnabled(False)
        item = self.top_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.top_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.top_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.top_table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.top_table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.top_table.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.top_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.top_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.top_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column"))
        __sortingEnabled = self.top_table.isSortingEnabled()
        self.top_table.setSortingEnabled(False)
        item = self.top_table.item(0, 0)
        item.setText(_translate("MainWindow", "English"))
        item = self.top_table.item(0, 1)
        item.setText(_translate("MainWindow", "Persian"))
        item = self.top_table.item(0, 2)
        item.setText(_translate("MainWindow", "Italian"))
        item = self.top_table.item(1, 0)
        item.setText(_translate("MainWindow", "Dutch"))
        item = self.top_table.item(1, 1)
        item.setText(_translate("MainWindow", "Chinese"))
        item = self.top_table.item(1, 2)
        item.setText(_translate("MainWindow", "Portuguese"))
        item = self.top_table.item(2, 0)
        item.setText(_translate("MainWindow", "French"))
        item = self.top_table.item(2, 1)
        item.setText(_translate("MainWindow", "Japanese"))
        item = self.top_table.item(2, 2)
        item.setText(_translate("MainWindow", "Hindi"))
        item = self.top_table.item(3, 0)
        item.setText(_translate("MainWindow", "Arabic"))
        item = self.top_table.item(3, 1)
        item.setText(_translate("MainWindow", "German"))
        item = self.top_table.item(3, 2)
        item.setText(_translate("MainWindow", "Turkish"))
        item = self.top_table.item(4, 0)
        item.setText(_translate("MainWindow", "Spanish"))
        item = self.top_table.item(4, 1)
        item.setText(_translate("MainWindow", "Czech"))
        item = self.top_table.item(4, 2)
        item.setText(_translate("MainWindow", "Swedish"))
        item = self.top_table.item(5, 0)
        item.setText(_translate("MainWindow", "Russian"))
        item = self.top_table.item(5, 1)
        item.setText(_translate("MainWindow", "Pashto"))
        item = self.top_table.item(5, 2)
        item.setText(_translate("MainWindow", "Korean"))
        self.top_table.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.translate_tab), _translate("MainWindow", "مترجم"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.favorite_tab), _translate("MainWindow", "نشان‌شده‌ها"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.flash_cart_tab), _translate("MainWindow", "فلش‌کارت"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "راهنما"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.history_tab), _translate("MainWindow", "تاریخچه"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.setting_tab), _translate("MainWindow", "تنظیمات"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.about_tab), _translate("MainWindow", "درباره‌ ما"))


import flags_rc
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
